name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Check directory structure
        run: |
          pwd
          ls -la
          echo "Theme directory:"
          ls -la themes/

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.140.1'
          extended: true

      - name: Hugo version
        run: hugo version

      - name: Build Hugo Site
        env:
          HUGO_ENV: production
        run: |
          hugo --minify --debug
          echo "Build complete, checking output:"
          ls -la public/

      - name: Create CNAME
        run: |
          echo 'yingteng.me' > public/CNAME
          echo "CNAME created:"
          cat public/CNAME

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./public
          publish_branch: gh-pages