name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod (if needed)

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v1
        with:
          hugo-version: '0.140.1' # 使用你需要的 Hugo 版本

      - name: Build Hugo Site
        run: hugo --minify # Replace with your Hugo build command

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./public
          publish_branch: main # 指定分支为 main